#!/bin/bash

#SBATCH -N 2
#SBATCH -t 00:10:00
#SBATCH --sockets-per-node=2
#SBATCH --cores-per-socket=4

module purge

export CGO_CFLAGS='-I$OPENMPI/include'
export CGO_LDFLAGS='-L$OPENMPI/lib -lmpi'
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OPENMPI/lib 

$OPENMPI/bin/mpirun  $GOPATH/bin/example

